=== jrocher526/LMGSI/UD 4/Act 7/DTD/Editorial.dtd
<!ELEMENT informe (cabecera, datos)>
<!ELEMENT cabecera (descripcion, fecha)>
<!ELEMENT descripcion (#PCDATA)>
<!ELEMENT fecha (#PCDATA)>

<!ELEMENT datos (region+)>
<!ELEMENT region (trimestre+)>
<!ATTLIST region nombre (Norte | Centro | Sur) #REQUIRED>

<!ELEMENT trimestre (librosVendidos)>
<!ATTLIST trimestre numero (1 | 2 | 3 | 4) #REQUIRED>

<!ELEMENT librosVendidos (#PCDATA)>

=== jrocher526/LMGSI/UD 4/Act 7/XML/Editorial.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE informe SYSTEM "C:\Users\Jhona\Desktop\Instituto\Lenguaje de marca\UD 4\Act 7\DTD\Editorial.dtd">
<informe>
    <cabecera>

        <descripcion>Informe de ventas para las regiones Norte, Centro y Sur</descripcion>
        <fecha>30/12/2009</fecha>
    </cabecera>

    <datos>

        <region nombre="Norte">
            <trimestre numero="1">
                <librosVendidos>24000</librosVendidos>
            </trimestre>
            <trimestre numero="2">
                <librosVendidos>38600</librosVendidos>
            </trimestre>
            <trimestre numero="3">
                <librosVendidos>NO_INFO</librosVendidos>
            </trimestre>
            <trimestre numero="4">
                <librosVendidos>NO_INFO</librosVendidos>
            </trimestre>
        </region>

        <region nombre="Centro">
            <trimestre numero="1">
                <librosVendidos>NO_INFO</librosVendidos>
            </trimestre>
            <trimestre numero="2">
                <librosVendidos>16080</librosVendidos>
            </trimestre>
            <trimestre numero="3">
                <librosVendidos>25000</librosVendidos>
            </trimestre>
            <trimestre numero="4">
                <librosVendidos>NO_INFO</librosVendidos>
            </trimestre>
        </region>

        <region nombre="Sur">
            <trimestre numero="1">
                <librosVendidos>27000</librosVendidos>
            </trimestre>
            <trimestre numero="2">
                <librosVendidos>31400</librosVendidos>
            </trimestre>
            <trimestre numero="3">
                <librosVendidos>40100</librosVendidos>
            </trimestre>
            <trimestre numero="4">
                <librosVendidos>30000</librosVendidos>
            </trimestre>

        </region>

    </datos>

</informe>
