=== jrocher526/LMGSI/UD 4/Act 1/DTD/BlibliotecaDeLibros.dtd
<?xml version="1.0" encoding="UTF-8"?>
<!ELEMENT biblioteca (libro+)>
<!ELEMENT libro (titulo, autor, editorial, año, genero, isbn)>
<!ELEMENT titulo (#PCDATA)>
<!ELEMENT autor (#PCDATA)>
<!ELEMENT editorial (#PCDATA)>
<!ELEMENT año (#PCDATA)>
<!ELEMENT genero (#PCDATA)>
<!ELEMENT isbn (#PCDATA)>

=== jrocher526/LMGSI/UD 4/Act 1/XML/Biblioteca.xml
<?xml version="1.0" encoding="UTF-8"?>

<!DOCTYPE biblioteca SYSTEM "C:/Users/1DAW2425-07/Desktop/Instituto/Lenguaje de marca/UD 4/Act 1/DTD/BlibliotecaDeLibros.dtd">

<biblioteca>
  <libro>
    <titulo>El Señor de los Anillos</titulo>
    <autor>J.R.R. Tolkien</autor>
    <editorial>Minotauro</editorial>
    <año>1954</año>
    <genero>Fantasía</genero>
    <isbn>978-8435065442</isbn>
  </libro>

  <libro>
    <titulo>1984</titulo>
    <autor>George Orwell</autor>
    <editorial>Debolsillo</editorial>
    <año>1949</año>
    <genero>Ciencia ficción</genero>
    <isbn>978-8497597671</isbn>
  </libro>

  <libro>
    <titulo>Harry Potter y la piedra filosofal</titulo>
    <autor>J.K. Rowling</autor>
    <editorial>Salamandra</editorial>
    <año>1997</año>
    <genero>Fantasía</genero>
    <isbn>978-8478884284</isbn>
  </libro>

  <libro>
    <titulo>Cien años de soledad</titulo>
    <autor>Gabriel García Márquez</autor>
    <editorial>Editorial Sudamericana</editorial>
    <año>1967</año>
    <genero>Realismo mágico</genero>
    <isbn>978-8437608868</isbn>
  </libro>

  <libro>
    <titulo>Don Quijote de la Mancha</titulo>
    <autor>Miguel de Cervantes</autor>
    <editorial>Espasa</editorial>
    <año>1605</año>
    <genero>Novela</genero>
    <isbn>978-8467003282</isbn>
  </libro>

  <libro>
    <titulo>El Principito</titulo>
    <autor>Antoine de Saint-Exupéry</autor>
    <editorial>Rey Lear</editorial>
    <año>1943</año>
    <genero>Fábula</genero>
    <isbn>978-9870000703</isbn>
  </libro>

  <libro>
    <titulo>Fahrenheit 451</titulo>
    <autor>Ray Bradbury</autor>
    <editorial>Minotauro</editorial>
    <año>1953</año>
    <genero>Ciencia ficción</genero>
    <isbn>978-8435065565</isbn>
  </libro>

  <libro>
    <titulo>La sombra del viento</titulo>
    <autor>Carlos Ruiz Zafón</autor>
    <editorial>Planeta</editorial>
    <año>2001</año>
    <genero>Novela histórica</genero>
    <isbn>978-8408058583</isbn>
  </libro>

  <libro>
    <titulo>Los detectives salvajes</titulo>
    <autor>Roberto Bolaño</autor>
    <editorial>Anagrama</editorial>
    <año>1998</año>
    <genero>Novela</genero>
    <isbn>978-8433960236</isbn>
  </libro>

  <libro>
    <titulo>El código Da Vinci</titulo>
    <autor>Dan Brown</autor>
    <editorial>Planeta</editorial>
    <año>2003</año>
    <genero>Thriller</genero>
    <isbn>978-8408094871</isbn>
  </libro>

</biblioteca>
