=== jrocher526/LMGSI/UD 4/Act 6/DTD/CFGS.dtd
<!ELEMENT Modulos (Modulo+)>
<!ELEMENT Modulo (Contenidos)>
<!ATTLIST Modulo nombre CDATA #REQUIRED>
<!ELEMENT Contenidos (UnidadDidactica+)>
<!ELEMENT UnidadDidactica (Nombre)>
<!ATTLIST UnidadDidactica tipo (Teorica | Practica) #REQUIRED
          descripcion CDATA #REQUIRED>
<!ELEMENT Nombre (#PCDATA)>

=== jrocher526/LMGSI/UD 4/Act 6/XML/CFGS.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE Modulos SYSTEM "C:\Users\Jhona\Desktop\Instituto\Lenguaje de marca\UD 4\Act 6\DTD\CFGS.dtd">
<Modulos>
    <Modulo nombre="Desarrollo de Aplicaciones Web">
        <Contenidos>
            <UnidadDidactica tipo="Teorica" descripcion="Introduccion a las tecnologias web.">
                <Nombre>UD1 - Tecnologias Web</Nombre>
            </UnidadDidactica>
            <UnidadDidactica tipo="Practica" descripcion="Desarrollo de paginas web con HTML, CSS y JavaScript.">
                <Nombre>UD2 - Desarrollo Frontend</Nombre>
            </UnidadDidactica>
        </Contenidos>
    </Modulo>

    <Modulo nombre="Programacion">
        <Contenidos>
            <UnidadDidactica tipo="Teorica" descripcion="Conceptos basicos de programacion en Java.">
                <Nombre>UD1 - Introduccion a la Programacion</Nombre>
            </UnidadDidactica>
            <UnidadDidactica tipo="Practica" descripcion="Programacion de aplicaciones en Java.">
                <Nombre>UD2 - Programacion en Java</Nombre>
            </UnidadDidactica>
        </Contenidos>
    </Modulo>

    <Modulo nombre="Bases de Datos">
        <Contenidos>
            <UnidadDidactica tipo="Teorica" descripcion="Conceptos fundamentales sobre bases de datos relacionales.">
                <Nombre>UD1 - Introduccion a las Bases de Datos</Nombre>
            </UnidadDidactica>
            <UnidadDidactica tipo="Practica" descripcion="Modelado de bases de datos con SQL.">
                <Nombre>UD2 - Diseño de Bases de Datos</Nombre>
            </UnidadDidactica>
        </Contenidos>
    </Modulo>

    <Modulo nombre="Sistemas Informaticos">
        <Contenidos>
            <UnidadDidactica tipo="Teorica" descripcion="Arquitectura de ordenadores y sistemas operativos.">
                <Nombre>UD1 - Fundamentos de Sistemas Informaticos</Nombre>
            </UnidadDidactica>
            <UnidadDidactica tipo="Practica" descripcion="Instalacion y configuracion de sistemas operativos.">
                <Nombre>UD2 - Administracion de Sistemas Operativos</Nombre>
            </UnidadDidactica>
        </Contenidos>
    </Modulo>

    <Modulo nombre="Entornos de Desarrollo">
        <Contenidos>
            <UnidadDidactica tipo="Teorica" descripcion="Herramientas y entornos de desarrollo de software.">
                <Nombre>UD1 - Herramientas de Desarrollo</Nombre>
            </UnidadDidactica>
            <UnidadDidactica tipo="Practica" descripcion="Desarrollo de aplicaciones utilizando entornos de desarrollo integrados (IDE).">
                <Nombre>UD2 - Programacion con Entornos de Desarrollo</Nombre>
            </UnidadDidactica>
        </Contenidos>
    </Modulo>

    <Modulo nombre="Desarrollo de Interfaces">
        <Contenidos>
            <UnidadDidactica tipo="Teorica" descripcion="Principios y fundamentos del diseño de interfaces de usuario.">
                <Nombre>UD1 - Diseño de Interfaces</Nombre>
            </UnidadDidactica>
            <UnidadDidactica tipo="Practica" descripcion="Creacion de interfaces utilizando tecnologias web y herramientas graficas.">
                <Nombre>UD2 - Desarrollo de Interfaces de Usuario</Nombre>
            </UnidadDidactica>
        </Contenidos>
    </Modulo>

    <Modulo nombre="Acceso a Datos">
        <Contenidos>
            <UnidadDidactica tipo="Teorica" descripcion="Conceptos sobre acceso y manipulacion de datos en aplicaciones.">
                <Nombre>UD1 - Introduccion al Acceso a Datos</Nombre>
            </UnidadDidactica>
            <UnidadDidactica tipo="Practica" descripcion="Acceso y manipulacion de datos en bases de datos mediante JDBC y otras tecnologias.">
                <Nombre>UD2 - Acceso a Datos con JDBC</Nombre>
            </UnidadDidactica>
        </Contenidos>
    </Modulo>

    <Modulo nombre="Proyecto de Desarrollo de Aplicaciones">
        <Contenidos>
            <UnidadDidactica tipo="Teorica" descripcion="Metodologias agiles y planificacion de proyectos de software.">
                <Nombre>UD1 - Metodologias de Desarrollo</Nombre>
            </UnidadDidactica>
            <UnidadDidactica tipo="Practica" descripcion="Desarrollo de un proyecto de software completo de acuerdo con los requisitos del cliente.">
                <Nombre>UD2 - Proyecto Final de Desarrollo</Nombre>
            </UnidadDidactica>
        </Contenidos>
    </Modulo>
</Modulos>
